# Generated by Django 6.0.1 on 2026-02-06 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LIKE', 'LIKE'), ('PASS', 'PASS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['from_user', 'created_at'], name='swipe_swipe_from_us_edf529_idx'), models.Index(fields=['to_user', 'created_at'], name='swipe_swipe_to_user_9b34bd_idx'), models.Index(fields=['from_user', 'to_user'], name='swipe_swipe_from_us_bddf6c_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='uniq_swipe_pair'), models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='no_self_swipe')],
            },
        ),
    ]
