# Generated by Django 6.0.1 on 2026-02-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipeaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
