# Generated by Django 6.0.1 on 2026-02-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_plan_expire_at_user_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
