# Generated by Django 6.0.1 on 2026-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PRIVACY', 'Privacy Policy'), ('TERMS', 'Terms & Conditions')], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('version', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
