# Generated by Django 6.0.1 on 2026-02-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userprofile_time_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time_range',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
