# Generated by Django 6.0.1 on 2026-02-16 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_time_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='time_range',
        ),
    ]
