# Generated by Django 6.0.1 on 2026-02-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_userprofile_time_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
